# Generated by Django 3.1.3 on 2020-12-02 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminprofile',
            table='adminprof',
        ),
    ]
